### ISSUE TITLE
Unable to Use USB Webcam with UVCCameraViewParamsEntity

### ISSUE THREAD

**Issue by AhmedHodiani** [chenyeju295/flutter_uvc_camera#1]
lsusb output:
Bus 001 Device 033: ID 1c4f:3002 SiGma Micro WebCam SiGma Micro

vendorId 1c4f
productId 3002

device_filter.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<usb>
    <usb-device vendor-id="1c4f" product-id="3002" />
</usb>
```

the UVCCameraViewParamsEntity takes List of ints for productIds and vendorIds

I tried converting from hex to decimal, but also not working.

**Comment by chenyeju295** [comment]
该插件仅支持安卓系统。提供 VendorId 和 ProductId 用于筛选，但它们是可选的。
