### ISSUE TITLE
Can't detect the press button event correctly

### ISSUE THREAD

**Issue by fabiologicALG** [chenyeju295/flutter_uvc_camera#11]
Hi, I'm using this package to be able to show the output from an external usb camera and to take a picture when the button on the external camera is pressed.
The output of the camera is correct while the button tap doesn't work correctly.

When I press the button for the first time this is the output of the console:
```
I/CameraView(18813): 点击了设备按钮：button=1 state=1
I/flutter (18813): ------> Received from Android：{msg: 开始拍照, type: msg}
I/flutter (18813): 开始拍照
I/CameraView(18813): 点击了设备按钮：button=1 state=0
I/flutter (18813): ------> Received from Android：{msg: 拍照失败：Failed to save image, type: onError}
```

Then, if I press the button another time this is what i receive:
```
I/CameraView(18813): 点击了设备按钮：button=1 state=1
I/CameraView(18813): 点击了设备按钮：button=1 state=0
```

 I'm not a Kotlin dev but I looked in the Kotlin code and seems to me that the path is missing. Isn't it? The function is _takePicture_:

```
fun takePicture(callback: UVCPictureCallback) {
        if (!isCameraOpened()) {
            callFlutter("摄像头未打开")
            setCameraERRORState("设备未打开")
            return
        }
        captureImage( object : ICaptureCallBack {
            override fun onBegin() {
                callFlutter("开始拍照")
            }

            override fun onComplete(path: String?) {
                if (path != null) {
                    callback.onPictureTaken(path)
                    MediaScannerConnection.scanFile(view.context, arrayOf(path), null) {
                            mPath, uri ->
                        // 文件已经被扫描到媒体数据库
                        println("Media scan completed for file: $mPath with uri: $uri")
                    }
                } else {
                    callback.onError("拍照失败，未能保存图片")
                }
            }
            override fun onError(error: String?) {
                callback.onError(error ?: "未知错误")
            }

        })
    }
```

Do you have any suggestion/workaround how to take correctly a image when the camera button is pressed?

**Comment by chenyeju295** [comment]
`Failed to save image` I think it's because of permissions?  What kind of device do you have?

**Comment by fabiologicALG** [comment]
Hi, thanks for the fast answer.
The model of my mobile device is Xiaomi Mi A1, Android Version 9.
When calling `cameraController?.takePicture()` it gives this exception: `PlatformException (PlatformException(error, Failed to save image, Failed to save image, null))`, as you said.

These are the permission that I put inside `AndroidManifest.xml`:

```
  <uses-permission android:name="android.permission.USB_PERMISSION" />
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-feature android:name="android.hardware.usb.host" />
  <uses-feature android:name="android.hardware.camera" />
  <uses-feature android:name="android.hardware.camera.autofocus" />
```

And for the device filter:
```
<intent-filter>
   <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
</intent-filter>

<meta-data
   android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
   android:resource="@xml/device_filter" 
/>
```

**Comment by chenyeju295** [comment]
Hi! Try installing the apk for this demo and try to see if you get this permissions issue (https://github.com/jiangdongguo/AndroidUSBCamera?tab=readme-ov-file#demo), I've modified his code for saving images, but I haven't tested it on android phones below version 11, help me troubleshoot and see if it's my problem.

**Comment by fabiologicALG** [comment]
Hi, I've tried to install the apk. 
The camera view is working correctly, while when i press the button nothing is happening.
The "take-a-picture" botton inside the app is working, it takes photos and save them without problems. 

I think there's a problem in the save date of the pictures, it says 08-11-643366 instead of 05-22-2024.
Let me know what can I do, thank you for your help.

**Comment by fabiologicALG** [comment]
Hello, I've tried to copy the plugin folder and to add some comments and console outputs to see where was the error. 
I've figured out that in the file [```flutter_uvc_camera/android/src/main/kotlin/com/chenyeju/UVCCameraView.kt```](https://github.com/chenyeju295/flutter_uvc_camera/blob/master/android/src/main/kotlin/com/chenyeju/UVCCameraView.kt#L515) at row 515, the function ```takePicture``` goes into the `onError` callback saying this: `Failed to save image`. I've also tried to specify the savePath, but it hasn't seemed to work.
The `captureImage` of row 506 goes trought `onBegin` but then failed in `onError` before enter in `onComplete`.

I've searched in the repo of this package and in the AndroidUSBCamera one but I didn't find any line saying "Failed to save image"

**Comment by chenyeju295** [comment]
hi! You can download this [Android project](https://github.com/chenyeju295/AndroidUSBCamera) to debug it, where you can find `Failed to save image`.

**Comment by chenyeju295** [comment]
Here's the address of the original author's project (https://github.com/jiangdongguo/AndroidUSBCamera), he seems to have this problem as well. You can take a look, I don't have android 9 so I wasn't able to debug it, sorry about that. @fabiologicALG

**Comment by fabiologicALG** [comment]
Thank you, in the next days I'll download the project and try to test it.
I'll let you know.

Have a good day!
