### ISSUE TITLE
[FLUTTER RELEASE MODE] Error: java.lang.NoSuchMethodError: no static or non-static method "Lcom/jiangdg/uvc/UVCCamera;.

### ISSUE THREAD

**Issue by DimaLiubko** [chenyeju295/flutter_uvc_camera#13]
Hey!

When I try to run app on flutter release mode I see this issue and app crashed

`I/flutter (31291): ------> UVCCameraController init
E/AndroidRuntime(31291): FATAL EXCEPTION: camera-1716391398718
E/AndroidRuntime(31291): Process: com.appName.prod, PID: 31291
E/AndroidRuntime(31291): java.lang.NoSuchMethodError: no static or non-static method "Lcom/jiangdg/uvc/UVCCamera;.nativeSetStatusCallback(JLcom/jiangdg/uvc/IStatusCallback;)I"
E/AndroidRuntime(31291): 	at java.lang.Runtime.nativeLoad(Native Method)
E/AndroidRuntime(31291): 	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
E/AndroidRuntime(31291): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
E/AndroidRuntime(31291): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/AndroidRuntime(31291): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(31291): 	at com.jiangdg.uvc.UVCCamera.<clinit>(SourceFile:5)
E/AndroidRuntime(31291): 	at e2.i.O(SourceFile:9)
E/AndroidRuntime(31291): 	at wa.f$c$b.a(SourceFile:3)
E/AndroidRuntime(31291): 	at cb.f.z(SourceFile:11)
E/AndroidRuntime(31291): 	at wa.f$c.handleMessage(SourceFile:47)
E/AndroidRuntime(31291): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31291): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime(31291): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime(31291): 	at android.os.HandlerThread.run(HandlerThread.java:67)`

<img width="1464" alt="external_camera_screen dart 2024-05-22 18-30-43" src="https://github.com/chenyeju295/flutter_uvc_camera/assets/29432498/f6a91de0-5565-43d9-b9c6-fd5d771a9d39">

When I run app in flutter dev mode all things work fine, I can see video from external cameras

How to fix it?

Was tested on:
Device: Android 14 - Samsung A55
External cameras: #1 Logitec / #2 Endoscop / #3 no_name

UPD
Both versions: flutter_uvc_camera 0.0.3 and 0.0.2

**Comment by chenyeju295** [comment]
@DimaLiubko  run release 遇到`NoSuchMethodError` ，通常是混淆了方法或字段。你可以在你的项目添加规则避免混淆关键的类、方法和字段。

- 添加文件 `proguard-rules.pro` 在你的android/src 
`-keep class com.jiangdg.uvc.UVCCamera {
    native <methods>;
    long mNativePtr;
}
-keep class com.jiangdg.uvc.IStatusCallback {
    *;
}
`

- 修改build.gradle，添加
`
    buildTypes {
        release {
            ...

            **proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            minifyEnabled true**

        }
    }`

**Comment by dtorologic** [comment]
@DimaLiubko Hello, have you been able to solve it?

**Comment by DimaLiubko** [comment]
> @DimaLiubko hi! run release encounters a `NoSuchMethodError` , usually an obfuscated method or field. You can add rules to your project to avoid obfuscating critical classes, methods and fields. You can take a look at this [commit](https://github.com/chenyeju295/flutter_uvc_camera/commit/aae3fcd8cfc2df074200bd11f89387d60918401b)

@chenyeju295 Hi!
Thanks for your response. 
I checked it with your last changes/commit and it not working. App crashed when I try to open external camera on release build

Here is an issue

```
I/flutter (27351): ------> UVCCameraController init
E/AndroidRuntime(27351): FATAL EXCEPTION: camera-1716798578855
E/AndroidRuntime(27351): Process: com.demoApp.prod, PID: 27351
E/AndroidRuntime(27351): java.lang.NoSuchMethodError: no static or non-static method "Lcom/jiangdg/uvc/UVCCamera;.nativeSetStatusCallback(JLcom/jiangdg/uvc/IStatusCallback;)I"
E/AndroidRuntime(27351): 	at java.lang.Runtime.nativeLoad(Native Method)
E/AndroidRuntime(27351): 	at java.lang.Runtime.nativeLoad(Runtime.java:1126)
E/AndroidRuntime(27351): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1080)
E/AndroidRuntime(27351): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
E/AndroidRuntime(27351): 	at java.lang.System.loadLibrary(System.java:1661)
E/AndroidRuntime(27351): 	at com.jiangdg.uvc.UVCCamera.<clinit>(SourceFile:5)
E/AndroidRuntime(27351): 	at e2.i.O(SourceFile:9)
E/AndroidRuntime(27351): 	at wa.f$c$b.a(SourceFile:3)
E/AndroidRuntime(27351): 	at cb.f.z(SourceFile:11)
E/AndroidRuntime(27351): 	at wa.f$c.handleMessage(SourceFile:47)
E/AndroidRuntime(27351): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27351): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime(27351): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime(27351): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```
