### ISSUE TITLE
camera on, but it doesn't show anything

### ISSUE THREAD

**Issue by dtorologic** [chenyeju295/flutter_uvc_camera#14]
Hello, I have two web cams, one of them works fine, and the other tells me that it is open, but it doesn't show anything. 

I leave you the debug, in case it helps:

`I/UVCCamera( 6796): open camera status: -5476376628106891136, size: {"formats":[{"index":1,"type":6,"default":1,"size":["1280x720"]}]}
I/CameraUVC( 6796): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=1280, height=720)], 
I/CameraUVC( 6796): getSuitableSize: PreviewSize(width=1280, height=720)
I/CameraUVC( 6796): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=1280, height=720)], 
I/MultiCameraClient( 6796): Audio record by using system mic
2
I/CameraUVC( 6796): aspect ratio = null, getAllPreviewSizes = [PreviewSize(width=1280, height=720)], 
E/CameraUVC( 6796):  setPreviewSize failed, try to use yuv format...
E/libUVCCamera( 6796): [10190*UVCPreview.cpp:524:prepare_preview]:could not negotiate with camera:err=-51
I/CameraUVC( 6796):  start preview, name = /dev/bus/usb/001/003, preview=PreviewSize(width=1280, height=720)
I/RenderManager( 6796): create camera SurfaceTexture: android.graphics.SurfaceTexture@4cdbf8
I/CameraView( 6796): ------>CameraState: OPENED
I/flutter ( 6796): Camera: OPENED
`

And a short video:

https://github.com/chenyeju295/flutter_uvc_camera/assets/156773579/81f3b545-d68f-4ee2-83a2-150e1fed0eb3

**Comment by Joao-Peterson** [comment]
Probably related to this issue: #7

**Comment by dtorologic** [comment]
> Probably related to this issue: #7  

Was it solved?

**Comment by chenyeju295** [comment]
> > Probably related to this issue: #7
> 
> Was it solved?

Try modifying 'frameFormat' to 1 or removing the passed parameter.
https://github.com/chenyeju295/flutter_uvc_camera/blob/master/example/lib/camera.dart`` 
![image](https://github.com/chenyeju295/flutter_uvc_camera/assets/147475251/00bccd79-04f8-4146-b7ed-39ec7f42fc7d)

**Comment by dtorologic** [comment]
> > > Probablemente relacionado con este problema: #7
> > 
> > 
> > ¿Se solucionó?
> 
> Intente modificar 'frameFormat' a 1 o eliminar el parámetro pasado. [https://github.com/chenyeju295/flutter_uvc_camera/blob/master/example/lib/camera.dart``](https://github.com/chenyeju295/flutter_uvc_camera/blob/master/example/lib/camera.dart%60%60) ![imagen](https://private-user-images.githubusercontent.com/147475251/333489468-00bccd79-04f8-4146-b7ed-39ec7f42fc7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzU4NDAsIm5iZiI6MTcxNjUzNTU0MCwicGF0aCI6Ii8xNDc0NzUyNTEvMzMzNDg5NDY4LTAwYmNjZDc5LTA0ZjgtNDE0Ni1iN2VkLTM5ZWM3ZjQyZmM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNzI1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2RlZWIwZWNjMDlkMzM1M2UwODRkNTJmMzU3ZmMzYTE3ZmRmMDhkZDRiYmIxMDM0YmVjNmMwZWQ2OWUxMWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kBmS88U4VuwPh7H-Ro4fYKJKUT1FZbjF78X88iOB580)

Its work!! Thanks!
