### ISSUE TITLE
多个USB摄像头如何设置选用?

### ISSUE THREAD

**Issue by hs19940808** [chenyeju295/flutter_uvc_camera#24]
请问多个USB摄像头如何设置选用?我在源码里没有找到对应的设置项

**Comment by lsmayday** [comment]
同问

**Comment by lsmayday** [comment]
> > 同问
> 
> 已经解决了，重写UVCCameraView.kt的registerMultiCamera方法，在连接设备时指定pid vid

可以具体说明一下吗？感激不尽
