### ISSUE TITLE
Add ProGuard Rules to Documentation for clickTakePictureButtonCallback

### ISSUE THREAD

**Issue by sofindersky** [chenyeju295/flutter_uvc_camera#28]
When testing the app in debug mode, I added the following code in the initState method to handle the button tap for taking a photo:

```
@override
void initState() {
  super.initState();
  cameraController = UVCCameraController();
  cameraController?.clickTakePictureButtonCallback = (String path) {
    // Perform some method
  };
}
```

This worked perfectly in debug mode, but in release mode, the clickTakePictureButtonCallback did not seem to work.

After some investigation and reviewing the documentation provided about ProGuard rules, I added IButtonCallback and related rules to the proguard-rules.pro file, and it worked!

```

-keep interface com.jiangdg.uvc.IButtonCallback {
    *;
    }
```
    
Could you please consider adding these ProGuard rules to the README?

**Comment by chenyeju295** [comment]
Okay. Thank you.
