### ISSUE TITLE
Could not find com.github.chenyeju295.AndroidUSBCamera:libausbc:3.3.6.

### ISSUE THREAD

**Issue by RuanCardoso** [chenyeju295/flutter_uvc_camera#3]
> Could not find com.github.chenyeju295.AndroidUSBCamera:libausbc:3.3.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/chenyeju295/AndroidUSBCamera/libausbc/3.3.6/libausbc-3.3.6.pom
       - https://repo.maven.apache.org/maven2/com/github/chenyeju295/AndroidUSBCamera/libausbc/3.3.6/libausbc-3.3.6.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/chenyeju295/AndroidUSBCamera/libausbc/3.3.6/libausbc-3.3.6.pom
     Required by:
         project :app > project :flutter_uvc_camera
   > Could not find com.github.chenyeju295.AndroidUSBCamera:libuvc:3.3.6.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/chenyeju295/AndroidUSBCamera/libuvc/3.3.6/libuvc-3.3.6.pom
       - https://repo.maven.apache.org/maven2/com/github/chenyeju295/AndroidUSBCamera/libuvc/3.3.6/libuvc-3.3.6.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/chenyeju295/AndroidUSBCamera/libuvc/3.3.6/libuvc-3.3.6.pom
       
How to fix this?
       
 [UPDATE 29/04/2023]

 - I posted the solution in the comments below.

**Comment by JyoHuang** [comment]
encountered  the same issue

**Comment by RuanCardoso** [comment]
> encountered the same issue

The solution is:

Download this: https://github.com/chenyeju295/flutter_uvc_camera

work with the example project found inside the "example" folder, modify it and be happy.

**Comment by JyoHuang** [comment]
Excuse me, Is there any way not to go through this folder? For example, copying some folder files or something like that? thank you very much

**Comment by RuanCardoso** [comment]
> Excuse me, Is there any way not to rely on this folder? For example, copying some folder files or something like that? thank you very much

You can use your own project, just point the library path correctly.

```bash
flutter_uvc_camera:
    path: **YOUR_PATH**
```
Download the lib here: https://github.com/chenyeju295/flutter_uvc_camera

**Comment by chenyeju295** [comment]
@JyoHuang @RuanCardoso  
Add the repositories library address to your main Android project。
` maven { url "https://jitpack.io" }`
<img width="447" alt="image" src="https://github.com/chenyeju295/flutter_uvc_camera/assets/147475251/3b0bf9e5-8a79-4403-8704-c20775a364bf">

**Comment by chenyeju295** [comment]
It was an oversight on my part. I'll update the README.md

**Comment by vaishnavijlk** [comment]
I'm facing the same issue, how do I use this plugin?

**Comment by chenyeju295** [comment]
@vaishnavijlk  It looks like the referenced packages are conflicting, you can remove the reference to"jiangdongguo.AndroidUSBCamera:3.3.3" .
which I forked from it ,  upgraded to 3.3.6 to support Android 14

**Comment by vaishnavijlk** [comment]
@chenyeju295, I followed the instructions from https://pub.dev/packages/flutter_uvc_camera and trying to integrate this in my project. I'm not able to run the app, I'm still getting the errors which I attached above. 
I'm using flutter_uvc_camera: ^0.0.2

**Comment by chenyeju295** [comment]
@vaishnavijlk  There may be other packages in your project that reference AndroidUSBCamera:libausbc:3.3.3, you can either do a global search to find them and remove the reference or try replacing the implementation with compileOnly. 
<img width="761" alt="image" src="https://github.com/chenyeju295/flutter_uvc_camera/assets/147475251/e8e3f64d-13a5-42f4-9b1c-560ed5d7747e">
