### ISSUE TITLE
Get permission failed in mUsbReceiver

### ISSUE THREAD

**Issue by DimaLiubko** [chenyeju295/flutter_uvc_camera#4]
Hi!

I'm trying to use your plugin, but when I give permission for the external USB camera in application I see the log 'get permission failed in mUsbReceiver'. 
After that  video stream is not working at all.

Here is short demo: [demo](https://monosnap.com/file/NPsAmgclGapXOekglWV5WCGQPXXn46)

How to fix it?

**Comment by chenyeju295** [comment]
The issue might be caused by using the emulator. Emulators sometimes don't accurately simulate USB-related functionalities. I suggest trying your app on a real device to see if the problem persists.

**Comment by DimaLiubko** [comment]
Hi!
Thanks for the reply. 
My demo was on a real Android device via (Vysor mirror).
The problem occurred on Android 10. 
On Android 14 it works fine.

**Comment by chenyeju295** [comment]
I got it, android 10 adjusts the security level, for apk using third party uvccamera library, if the compiled apk `targetSdkVersion` version is greater than or equal to 28, android 10 can't get the permission to call USB camera! If you want to run it on Android 10, you need to lower the `targetSdkVersion` to 27 to be able to do so. Thank you, I'll update the readme.
