### ISSUE TITLE
Not find pid & vid

### ISSUE THREAD

**Issue by dtorologic** [chenyeju295/flutter_uvc_camera#6]
It does not find the device after passing the pid and vid parameters to it.

**Comment by chenyeju295** [comment]
Hi! Could you please provide me with more information about your issue, error logs, device information, and so on

**Comment by dtorologic** [comment]
> Hi! Could you please provide me with more information about your issue, error logs, device information, and so on

To get the pid and vid I do the following on my Windows. Devices -> Cameras -> I select my camera -> Details -> Hardware ID. And I get these results: **USB\VID_046D&PID_082B&REV_2825&MI_00
USB\VID_046D&PID_082B&MI_00**

**In the class camera.dart:**

`      SizedBox(
                child: UVCCameraView(
                  cameraController: cameraController!,
                  params: const UVCCameraViewParamsEntity(
                    aspectRatio: 1,
                    productIds: [0x822B],
                    vendorIds: [0x046D],
                  ),
                  width: 300,
                  height: 300,
                ),
              ),`

**And in the device_filter.xml class:**

`<?xml version="1.0" encoding="utf-8"?>
    <usb>
        <usb-device vendor-id="046D" product-id="082B" /> 
    </usb>`

**This error for console:**
_V/USBMonitor(17629): USBMonitor:Constructor
V/USBMonitor(17629): USBMonitor:mUsbManager=android.hardware.usb.UsbManager@8a412c1
I/MultiCameraClient(17629): register...
I/USBMonitor(17629): register:
E/FrameEvents(17629): updateAcquireFence: Did not find frame.
I/flutter (17629): Camera: ERROR:未检测到设备
E/FrameEvents(17629): updateAcquireFence: Did not find frame.
I/flutter (17629): openUVCCamera
I/flutter (17629): Camera: ERROR:未检测到设备_


Thanks!!

**Comment by chenyeju295** [comment]
What Android model is running and what version of android is it running?  It may have something to do with the camera device or the model it's running on. The documentation on pid vid identification can be found at [USB host overview](https://developer.android.google.cn/develop/connectivity/usb/host?hl=en)

**Comment by dtorologic** [comment]
> What Android model is running and what version of android is it running?  It may have something to do with the camera device or the model it's running on. The documentation on pid vid identification can be found at [USB host overview](https://developer.android.google.cn/develop/connectivity/usb/host?hl=en)
> 

Hello, I have tested on two devices with different versions of Android. On a mobile device I have 14 UKQ1.230804.001 and on a tablet with version 13. I have installed the apk from your repository AUSBC3 and it works correctly for me.
