### ISSUE TITLE
saving photo directly to a variable

### ISSUE THREAD

**Issue by Danilo-Taveira** [chenyeju295/flutter_uvc_camera#9]
Hello,

I need to save the photo I took with the external camera in a variable, but I couldn't find a way to do it without saving it to the device's path. Is there a way?

**Comment by chenyeju295** [comment]
Hiya, do you just want to save the photos temporarily in the app cache instead of the device memory?

**Comment by Danilo-Taveira** [comment]
Hello,

I figured out how to solve this problem. Thanks!
